package com.miaupy.business.application;
import com.miaupy.business.domain.*;import com.miaupy.shared.exception.ResourceNotFoundException;import com.miaupy.shared.tenant.TenantContext;import java.math.BigDecimal;import java.time.ZoneId;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class BusinessConfigurationUseCase{
 private final TenantContext tenants;private final BusinessRepository businesses;private final BusinessConfigurationRepository configurations;public BusinessConfigurationUseCase(TenantContext t,BusinessRepository b,BusinessConfigurationRepository c){tenants=t;businesses=b;configurations=c;}
 @Transactional(readOnly=true)public BusinessSettings getSettings(){return configurations.findSettingsByTenantId(tenants.getRequiredTenantId()).orElseThrow(()->new ResourceNotFoundException("Business settings not found"));}
 @Transactional public BusinessSettings updateSettings(AppointmentApprovalMode mode,String timezone,String currency,boolean booking,boolean sales){Long tenant=tenants.getRequiredTenantId();requireBusiness(tenant);ZoneId.of(timezone);BusinessSettings value=configurations.findSettingsByTenantId(tenant).map(s->s.update(mode,timezone,currency,booking,sales)).orElseGet(()->BusinessSettings.create(tenant,mode,timezone,currency,booking,sales));return configurations.saveSettings(value);}
 @Transactional(readOnly=true)public BusinessAddress getAddress(){return configurations.findAddressByTenantId(tenants.getRequiredTenantId()).orElseThrow(()->new ResourceNotFoundException("Business address not found"));}
 @Transactional public BusinessAddress updateAddress(String street,String number,String district,String city,String state,String postal,BigDecimal lat,BigDecimal lon){Long tenant=tenants.getRequiredTenantId();Business business=requireBusiness(tenant);BusinessAddress value=configurations.findAddressByTenantId(tenant).map(a->a.update(street,number,district,city,state,postal,lat,lon)).orElseGet(()->BusinessAddress.create(tenant,business.id(),street,number,district,city,state,postal,lat,lon));return configurations.saveAddress(value);}
 private Business requireBusiness(Long tenant){return businesses.findByTenantId(tenant).orElseThrow(()->new ResourceNotFoundException("Business profile not found"));}}
